# This is an example config yaml file for:
#   BIDS App:         fMRIPrep ("fmriprep")
#   BIDS App version: 23.1.3
#   Task:             Preprocessing fMRI data with FreeSurfer results ingressed
#   Which system:     Slurm
#   Tested on which cluster:  UMN MSI cluster

# WARNING!!!
#   This is only an example, which may not necessarily fit your purpose,
#   or be an optimized solution for your case,
#   or be compatible to the BIDS App version you're using.
#   Therefore, please change and tailor it for your case before use it!!!

# Arguments in `singularity run`:
#   In this example, we assume:
#   1. You used BABS to run `fMRIPrep --anat-only` w/ fMRIPrep version 23.1.3, and used current BIDS output layout (default);
#   2. You have got output folder called `fmriprep_anat` (i.e., `zip_foldernames`: `fmriprep_anat`)
#   3. When running `babs-init` for current use case, argument `--input` for `babs-init` is as below:
#     --input BIDS <path/to/raw_BIDS_dataset>    # 1st input dataset \
#     --input fmriprep_anat <path/to/cloned_fmriprep_anat_output_ria>    # 2nd input dataset \
singularity_run:
    $INPUT_PATH: inputs/data/BIDS   # the key `$INPUT_PATH` is a placeholder, which must be included first as there are two input datasets
    -w: "$BABS_TMPDIR"   # this is a placeholder recognized by BABS.
    --n_cpus: '1'
    --stop-on-first-crash: ""
    --fs-license-file: "/home/faird/zhaoc/software/FreeSurfer/license.txt"  # [FIX ME] path to FS license file
    --skip-bids-validation: ""
    --output-spaces: MNI152NLin6Asym:res-2
    --force-bbr: ""
    --cifti-output: 91k
    -v: "-v"
    --fs-subjects-dir: inputs/data/fmriprep_anat/fmriprep_anat/sourcedata/freesurfer

# Output foldername(s) to be zipped, and the BIDS App version to be included in the zip filename(s):
#   As we are using BIDS output layout, we need to ask BABS to create a folder 'fmriprep' to wrap all derivatives:
zip_foldernames:
    $TO_CREATE_FOLDER: "true"
    fmriprep: "23-1-3"     # folder 'fmriprep' will be zipped into 'sub-xx_ses-yy_fmriprep-23-1-3.zip'

cluster_resources:
    interpreting_shell: "/bin/bash -l"
    hard_memory_limit: 24G
    number_of_cpus: '2'
    temporary_disk_space: 200G
    hard_runtime_limit: "96:00:00"   # note: max on MSI cluster  # TODO: what's preferred?
    customized_text: |
        #SBATCH -p amd2tb,ram256g
# Notes: Above `customized_text` is Penn Med CUBIC cluster specific.
#   So it's probably not relevant for other clusters

# Necessary commands to be run first:
script_preamble: |
    source /home/faird/shared/code/external/envs/miniconda3/load_miniconda3.sh   # [FIX ME] MSI cluster faird group. Replace filepath with yours.
    conda activate babs   # [FIX ME] replace 'babs' with your env variable name

# Where to run the jobs:
job_compute_space: "/tmp"   # [FIX ME] MSI cluster

# Below is to filter out subjects (or sessions). Only those with required files will be kept.
required_files:
    $INPUT_DATASET_#1:
        - "func/*_bold.nii*"
        - "anat/*_T1w.nii*"

# `alert_log_messages`: Here we did not provide examples for section `alert_log_messages`. However feel free to add it!
