# This is an example config yaml file for:
#   BIDS App:         fMRIPrep ("fmriprep")
#   BIDS App version: 24.1.1
#   Task:             Preprocessing fMRI data with FreeSurfer results ingressed
#   Which system:     SGE or Slurm

# WARNING!!!
#   This is only an example, which may not necessarily fit your purpose,
#   or be an optimized solution for your case,
#   or be compatible to the BIDS App version you're using.
#   Therefore, please change and tailor it for your case before use it!!!

# Arguments in `singularity run`:
#   In this example, we assume:
#   1. You used BABS to run `fMRIPrep --anat-only` w/ fMRIPrep version 23.1.3, and used current BIDS output layout (default);
#   2. From 1, you have got output folder called `fmriprep_anat` (i.e., `zip_foldernames`: `fmriprep_anat`; make sure you add `all_results_in_one_zip: true`)
#   3. When running `babs init` for current use case, argument `--datasets` for `babs init` is as below:
#     --datasets BIDS=<path/to/raw_BIDS_dataset>    # 1st input dataset \
#     fmriprep_anat=<path/to/cloned_fmriprep_anat_output_ria>    # 2nd input dataset \
bids_app_args:
    $SUBJECT_SELECTION_FLAG: "--participant-label"
    $INPUT_PATH: inputs/data/BIDS # the key `$INPUT_PATH` is a placeholder, which must be included first as there are two input datasets
    -w: "$BABS_TMPDIR"
    --stop-on-first-crash: ""
    --fs-license-file: "/path/to/FreeSurfer/license.txt" # [FIX ME] path to FreeSurfer license file
    --output-spaces: "func T1w MNI152NLin6Asym:res-2"
    --force-bbr: ""
    --skip-bids-validation: ""
    -vv: ""
    --cifti-output: "91k"
    --n_cpus: "4"
    --mem-mb: "30000"
    --fs-subjects-dir: inputs/data/fmriprep_anat/fmriprep_anat/sourcedata/freesurfer #replace with path to your freesurfer results from fmriprep_anat

# Arguments that are passed directly to singularity/apptainer:
singularity_args:
    - --containall
    - --writable-tmpfs

# Output foldername(s) to be zipped, and the BIDS App version to be included in the zip filename(s):
#   As fMRIPrep will use BIDS output layout, we need to ask BABS to create a folder 'fmriprep_anat' to wrap all derivatives:
all_results_in_one_zip: true
zip_foldernames:
    fmriprep_func: "24-1-1" # folder 'fmriprep_func' will be zipped into 'sub-xx_(ses-yy_)fmriprep_func-24-1-1.zip'

# How much cluster resources it needs:
cluster_resources:
    interpreting_shell: "/bin/bash"
    hard_runtime_limit: "7:00:00"
    temporary_disk_space: 200G
    customized_text: |
        #SBATCH -p all
        #SBATCH --nodes=1
        #SBATCH --ntasks=1
        #SBATCH --cpus-per-task=4
        #SBATCH --mem=30G
        #SBATCH --propagate=NONE

# Necessary commands to be run first:
#   [FIX ME] change or add commands for setting up the virtual environment, for loading necessary modules, etc
script_preamble: |
    source "${CONDA_PREFIX}"/bin/activate babs # you may need to change this to work with your environment manager.
    source xxxx    # [FIX ME or DELETE ME] source any necessary program
    module load xxxx # [FIX ME or DELETE ME] source any necessary program

# Where to run the jobs:
job_compute_space: "path/to/temporary_compute_space" # [FIX ME] replace "/path/to/temporary_compute_space" with yours

# Below is to filter out subjects (or sessions). Only those with required files will be kept.
required_files:
    $INPUT_DATASET_#1:
        - "func/*_bold.nii*"
        - "anat/*_T1w.nii*"

# Alert messages that might be found in log files of failed jobs:
#   These messages may be helpful for debugging errors in failed jobs.
alert_log_messages:
    stdout:
        - "Excessive topologic defect encountered"
        - "Cannot allocate memory"
        - "mris_curvature_stats: Could not open file"
        - "Numerical result out of range"
        - "fMRIPrep failed"
