# This is an example config yaml file for:
#   BIDS App:         fMRIPrep ("fmriprep")
#   BIDS App version: 20.2.3
#   Task:             Preprocessing fMRI data with FreeSurfer results ingressed, however in a sloppy mode!
#   Which system:     SGE
#   Tested on which cluster:  PennMed CUBIC cluster

# WARNING!!!
#   This is in `--sloppy` mode, which is for testing ONLY, NOT for generating productions used for research!

# WARNING!!!
#   This is only an example, which may not necessarily fit your purpose,
#   or be an optimized solution for your case,
#   or be compatible to the BIDS App version you're using.
#   Therefore, please change and tailor it for your case before use it!!!

# Arguments in `singularity run`:
#   In this example, we assume:
#   1. You used BABS to run `fMRIPrep --anat-only` w/ fMRIPrep version 20.2.3, which used legacy output layout
#   2. From 1, you have got output folder called `freesurfer` (i.e., `zip_foldernames`: `freesurfer`)
#   3. When running `babs-init` for current use case, argument `--input` for `babs-init` is as below:
#     --input BIDS <path/to/raw_BIDS_dataset>    # 1st input dataset \
#     --input freesurfer <path/to/cloned_freesurfer_output_ria>    # 2nd input dataset \
singularity_run:
    $INPUT_PATH: inputs/data/BIDS   # the key `$INPUT_PATH` is a placeholder, which must be included first as there are two input datasets
    -w: "$BABS_TMPDIR"   # this is a placeholder. To be changed to `${PWD}/.git/tmp/wkdir`
    --n_cpus: '1'
    --stop-on-first-crash: ""
    --fs-license-file: "/cbica/projects/BABS/software/FreeSurfer/license.txt"  # [FIX ME] path to FS license file
    --skip-bids-validation: ""
    --output-spaces: MNI152NLin6Asym:res-2
    --force-bbr: ""
    --cifti-output: 91k
    -v: "-v"
    --fs-subjects-dir: inputs/data/freesurfer/freesurfer
    --sloppy: ''      # ADD THIS WHEN TEST RUN!

# Output foldername(s) to be zipped, and the BIDS App version to be included in the zip filename(s):
zip_foldernames:
    fmriprep: "20-2-3"     # folder 'fmriprep' will be zipped into 'sub-xx_(ses-yy_)fmriprep-20-2-3.zip'

cluster_resources:
    interpreting_shell: /bin/bash
    hard_memory_limit: 24G
    number_of_cpus: '2'
    temporary_disk_space: 200G
    customized_text: |
        #$ -R y
        #$ -l hostname=!compute-fed*
# Notes: Above `customized_text` is Penn Med CUBIC cluster specific.
#   So it's probably not relevant for other clusters

# Necessary commands to be run first:
script_preamble: |
    source ${CONDA_PREFIX}/bin/activate mydatalad    # [FIX ME] Penn Med CUBIC cluster; replace 'mydatalad' with your conda env name

# Where to run the jobs:
job_compute_space: "${CBICA_TMPDIR}"   # Penn Med CUBIC cluster tmp space

# Below is to filter out subjects (or sessions). Only those with required files will be kept.
required_files:
    $INPUT_DATASET_#1:
        - "func/*_bold.nii*"
        - "anat/*_T1w.nii*"

# `alert_log_messages`: Here we did not provide examples for section `alert_log_messages`. However feel free to add it!
