# This is an example config yaml file for:
#   BIDS App:         freesurfer-post
#   BIDS App version: unstable
#   Task:             Creating tabular outputs from FreeSurfer results
#   Which system:     Slurm

# WARNING!!!
#   This is only an example, which may not necessarily fit your purpose,
#   or be an optimized solution for your case,
#   or be compatible to the BIDS App version you're using.
#   Therefore, please change and tailor it for your case before use it!!!

# Define the input datasets
input_datasets:
    FreeSurfer:
        required_files:
            - "*freesurfer*.zip"
        is_zipped: true
        origin_url: "/path/to/FreeSurfer"
        path_in_babs: inputs/data/freesurfer

bids_app_args:
    $SUBJECT_SELECTION_FLAG: "--participant-label"
    $SESSION_SELECTION_FLAG: "--session-id"
    -w: "$BABS_TMPDIR"
    --stop-on-first-crash: ""
    --fs-license-file: "/path/to/FreeSurfer/license.txt" # [FIX ME] path to FreeSurfer license file
    --fs-subjects-dir: '"$PWD"/inputs/data/fmriprep_anat/fmriprep_anat/sourcedata/freesurfer' #replace with path to your freesurfer results from fmriprep_anat

# Arguments that are passed directly to singularity/apptainer:
singularity_args:
    - --containall
    - --writable-tmpfs

# Output foldername(s) to be zipped, and the BIDS App version to be included in the zip filename(s):
all_results_in_one_zip: true
zip_foldernames:
    freesurfer-post: "unstable" # folder 'freesurfer-post' will be zipped into 'sub-xx_(ses-yy_)freesurfer-post-unstable.zip'

# How much cluster resources it needs:
cluster_resources:
    interpreting_shell: "/bin/bash"
    hard_runtime_limit: "0:30:00"
    temporary_disk_space: 5G
    customized_text: |
        #SBATCH -p all
        #SBATCH --nodes=1
        #SBATCH --ntasks=1
        #SBATCH --cpus-per-task=1
        #SBATCH --mem=5G
        #SBATCH --propagate=NONE

# Necessary commands to be run first:
#   [FIX ME] change or add commands for setting up the virtual environment, for loading necessary modules, etc
script_preamble: |
    source "${CONDA_PREFIX}"/bin/activate babs # you may need to change this to work with your environment manager.
    source xxxx    # [FIX ME or DELETE ME] source any necessary program
    module load xxxx # [FIX ME or DELETE ME] source any necessary program

# Where to run the jobs:
job_compute_space: "path/to/temporary_compute_space" # [FIX ME] replace "/path/to/temporary_compute_space" with yours
