name: Shellcheck scripts

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Set up system
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install shellcheck
    - uses: actions/checkout@v4
    - name: Run shellcheck
      run: |
        shellcheck \
        tests/e2e-slurm/container/babs-user-script.sh \
        tests/e2e-slurm/container/ensure-env.sh \
        tests/e2e-slurm/container/walkthrough-tests.sh \
        tests/e2e-slurm/install-babs.sh \
        tests/e2e-slurm/main.sh
